version: '2.29.2'

services:
  djangoappacross:
    container_name: djangoappAcross
    build:
      context: .
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/staticfiles:/data/web/staticfiles
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    networks:
      - crospy
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: always  # Adicionado para reiniciar automaticamente

  psqlAcross:
    container_name: psqlAcross
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
      - ./data/postgres/backups:/var/lib/postgresql/backups/
    env_file:
      - ./dotenv_files/.env
    networks:
      - crospy
    ports:
      - "54320:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: always  # Adicionado para reiniciar automaticamente

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/web/static:/data/web/static/
      - ./data/web/staticfiles:/data/web/staticfiles
      - ./data/web/media:/data/web/media/
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/certbot
    ports:
      - "1337:80"
      - "443:443"  # Porta 443 para SSL
    depends_on:
      - djangoappacross
    networks:
      - crospy
    restart: always  # Adicionado para reiniciar automaticamente

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always  # Adicionado para reiniciar automaticamente

networks:
  crospy:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
