version: '3.9'

services:
  djangoappacross:
    container_name: djangoappAcross
    build:
      context: .
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/staticfiles:/data/web/staticfiles
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    networks:
      - crospy
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  psqlAcross:
    container_name: psqlAcross
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
      - ./data/postgres/backups:/var/lib/postgresql/backups/
    env_file:
      - ./dotenv_files/.env
    networks:
      - crospy
    ports:
      - "54320:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1337:80"
    depends_on:
      - djangoappacross
    networks:
      - crospy

networks:
  crospy:
    driver: bridge