version: '2.29.2'

services:
  djangoappacross:
    container_name: djangoappAcross
    build:
      context: .
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/staticfiles:/data/web/staticfiles
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    networks:
      - crospy
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: always

  psqlAcross:
    container_name: psqlAcross
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
      - ./data/postgres/backups:/var/lib/postgresql/backups/
    env_file:
      - ./dotenv_files/.env
    networks:
      - crospy
    ports:
      - "54320:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/web/static:/data/web/static/
      - ./data/web/staticfiles:/data/web/staticfiles
      - ./data/web/media:/data/web/media/
      - ./data/certbot/conf:/etc/letsencrypt   # Certificados SSL manuais aqui
    ports:
      - "1337:80"
      - "8443:443"  # Porta 443 para SSL
    depends_on:
      - djangoappacross
    networks:
      - crospy
    restart: always

networks:
  crospy:
    driver: bridge
