# Generated by Django 5.0.1 on 2024-08-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='path',
            field=models.TextField(),
        ),
    ]
