# Generated by Django 5.0.1 on 2024-09-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='coupons_generated',
        ),
    ]
