# Generated by Django 5.0.1 on 2024-09-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0002_alter_accesslog_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agent_ip', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('coupons_generated', models.PositiveIntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
