# Generated by Django 5.0.1 on 2024-09-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0002_remove_agent_coupons_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='numcaixa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
