# Generated by Django 5.0.1 on 2024-09-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0002_alter_accesslog_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('agent_ip', models.CharField(max_length=100)),
                ('coupons_generated', models.PositiveIntegerField(default=0)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('uptime', models.DurationField(blank=True, null=True)),
                ('service_version', models.CharField(blank=True, max_length=100, null=True)),
                ('last_restart', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
