# Generated by Django 5.0.1 on 2024-09-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0003_agent_numcaixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDesactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcaixa', models.IntegerField(blank=True, null=True)),
                ('dtmov', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
