# Generated by Django 5.0.1 on 2024-09-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0003_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='status',
        ),
    ]
