# Generated by Django 5.0.1 on 2024-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable', '0004_agentdesactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='codfilial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
