# Generated by Django 5.0.1 on 2024-04-01 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='areaAtuacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='avaliacaoPerguntas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=150)),
                ('passo', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='cidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='estados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='pdv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=300)),
                ('cod_pdv', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='perguntasExecucao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=300)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='pilaresQuinzenais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='regional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='agendaMes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesAno', models.DateField()),
                ('id_gerente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendaMes_gerente', to=settings.AUTH_USER_MODEL)),
                ('id_gerenteGeral', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendaMes_gerenteGeral', to=settings.AUTH_USER_MODEL)),
                ('area_atuacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendaMes_area_atuacao', to='book.areaatuacao')),
            ],
            options={
                'db_table': 'agendaMes',
            },
        ),
        migrations.CreateModel(
            name='agendaSemana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_inicial', models.DateTimeField()),
                ('dt_final', models.DateTimeField(blank=True, null=True)),
                ('motivo_escolha', models.TextField(blank=True, max_length=500, null=True)),
                ('objetivo_principal', models.TextField(blank=True, max_length=500, null=True)),
                ('alteracoes', models.TextField(blank=True, max_length=500, null=True)),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('idagenda_mes', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book.agendames')),
            ],
            options={
                'db_table': 'agendaSemana',
            },
        ),
        migrations.CreateModel(
            name='agendaDia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('pauta', models.CharField(max_length=150)),
                ('realizado', models.BooleanField(blank=True, null=True)),
                ('id_agenda_semana', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agendaDia_agenda_semana', to='book.agendasemana')),
            ],
            options={
                'db_table': 'agendaDia',
            },
        ),
        migrations.CreateModel(
            name='analiseQuinzenal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes_ano', models.DateField()),
                ('quinzena', models.IntegerField(default=1)),
                ('id_gerente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='analiseQuinzenal_gerente', to=settings.AUTH_USER_MODEL)),
                ('id_gerente_geral', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='analiseQuinzenal_gerenteGeral', to=settings.AUTH_USER_MODEL)),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='analiseQuinzenal_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='anotacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vdd', models.IntegerField()),
                ('dt_inicial', models.DateField(blank=True, null=True)),
                ('dt_final', models.DateField(blank=True, null=True)),
                ('anotacoes', models.TextField(blank=True, max_length=15000, null=True)),
                ('obs', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/')),
                ('id_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='anotacoes_avaliado', to=settings.AUTH_USER_MODEL)),
                ('id_avaliador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='anotacoes_avaliador', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='anotacoes_cidade', to='book.cidades')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, max_length=5000, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cliente_cidade', to='book.cidades')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cliente_estado', to='book.estados')),
            ],
        ),
        migrations.CreateModel(
            name='execucao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_aval', models.DateField()),
                ('pdv', models.IntegerField(blank=True, null=True)),
                ('cod_fantasia', models.CharField(max_length=150)),
                ('fat_anterior', models.FloatField(blank=True, null=True)),
                ('fat_atual', models.FloatField(blank=True, null=True)),
                ('id_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='execucao_supervisor', to=settings.AUTH_USER_MODEL)),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='execucao_vendedor', to=settings.AUTH_USER_MODEL)),
                ('id_regional', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='execucao_regional', to='book.regional')),
            ],
        ),
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=300)),
                ('contato_fornec', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cgc', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('dt_bloqueio', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, max_length=300, null=True)),
                ('repre', models.TextField(blank=True, max_length=300, null=True)),
                ('repre_cel', models.CharField(blank=True, max_length=20, null=True)),
                ('repre_email', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_contato', models.CharField(blank=True, max_length=100, null=True)),
                ('rep_endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('rep_bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_uf', models.CharField(blank=True, max_length=2, null=True)),
                ('rep_cep', models.CharField(blank=True, max_length=10, null=True)),
                ('dt_cadastro', models.DateField(blank=True, null=True)),
                ('dt_exclusao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='book.cidades')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='book.estados')),
                ('rep_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rep_cidade', to='book.cidades')),
            ],
        ),
        migrations.CreateModel(
            name='observacoesExecucao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_obs', models.CharField(max_length=2)),
                ('descricao', models.TextField(max_length=300)),
                ('id_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoesExecucao_execucao', to='book.execucao')),
            ],
        ),
        migrations.CreateModel(
            name='oportunidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_inicial', models.DateField(blank=True, null=True)),
                ('dt_final', models.DateField(blank=True, null=True)),
                ('id_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='oportunidades_avaliado', to=settings.AUTH_USER_MODEL)),
                ('id_avaliador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='oportunidades_avaliador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='oportunidadeItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oque', models.TextField(blank=True, max_length=1500, null=True)),
                ('como', models.TextField(blank=True, max_length=1500, null=True)),
                ('quando', models.DateField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, max_length=1500, null=True)),
                ('reprogramacao', models.BooleanField(default=False)),
                ('dt_reprogramacao', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/')),
                ('id_oportunidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidadeItems_oportunidades', to='book.oportunidades')),
            ],
        ),
        migrations.CreateModel(
            name='problemasSolucoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_inicial', models.DateField(blank=True, null=True)),
                ('dt_final', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, max_length=5000, null=True)),
                ('id_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='problemasSolucoes_avaliado', to=settings.AUTH_USER_MODEL)),
                ('id_avaliador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='problemasSolucoes_avaliador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='problemasSolucoesItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problema', models.TextField(blank=True, max_length=1500, null=True)),
                ('solucao', models.TextField(blank=True, max_length=1500, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=2, null=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('id_problemas_solucoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemasSolucoesItems_problemas_solucoes', to='book.problemassolucoes')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre', models.TextField(blank=True, max_length=1000, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('aniversario', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cel', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1, null=True)),
                ('twitter', models.CharField(blank=True, max_length=150, null=True)),
                ('face', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='book.cidades')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='questionamentosQuinzenais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('id_pilar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questionamentosQuinzenais_pilar', to='book.pilaresquinzenais')),
            ],
        ),
        migrations.CreateModel(
            name='questRealizados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacao', models.TextField(blank=True, max_length=1000, null=True)),
                ('realizado', models.BooleanField(blank=True, null=True)),
                ('id_analise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questRealizados_analise', to='book.analisequinzenal')),
                ('id_quest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questRealizados_quest', to='book.questionamentosquinzenais')),
            ],
        ),
        migrations.CreateModel(
            name='resultadoExecucao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('executado', models.BooleanField(blank=True, null=True)),
                ('id_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultadoExecucao_execucao', to='book.execucao')),
                ('id_pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultadoExecucao_pdv', to='book.pdv')),
                ('id_perguntas_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultadoExecucao_perguntas_execucao', to='book.perguntasexecucao')),
            ],
        ),
        migrations.CreateModel(
            name='reuniao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('data', models.DateField()),
                ('horaInicial', models.TimeField(blank=True, null=True)),
                ('horaFinal', models.TimeField(blank=True, null=True)),
                ('tipoReuniao', models.CharField()),
                ('consideracao_final', models.TextField(blank=True, max_length=3000, null=True)),
                ('assinatura_supervisor', models.CharField(blank=True, max_length=150, null=True)),
                ('assinatura_lider', models.CharField(blank=True, max_length=150, null=True)),
                ('executo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reuniao_executo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pautas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, max_length=1500, null=True)),
                ('solucao', models.TextField(blank=True, max_length=1500, null=True)),
                ('id_reniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas_reniao', to='book.reuniao')),
            ],
        ),
        migrations.CreateModel(
            name='participantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('e_convidado', models.BooleanField(default=False)),
                ('assunto', models.TextField(blank=True, max_length=500, null=True)),
                ('participou', models.BooleanField(blank=True, null=True)),
                ('assinatura', models.CharField(blank=True, max_length=150, null=True)),
                ('id_fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='participantes_fornecedor', to=settings.AUTH_USER_MODEL)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='participantes_user', to=settings.AUTH_USER_MODEL)),
                ('id_reniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_reniao', to='book.reuniao')),
            ],
        ),
        migrations.CreateModel(
            name='rotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=150)),
                ('dt_inicial', models.DateField(blank=True, null=True)),
                ('dt_final', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rotas_representante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='avaliacaoitems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('realizado', models.BooleanField(blank=True, null=True)),
                ('dt_treino', models.DateField(blank=True, null=True)),
                ('id_avaliacao_perguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaoitems_avaliacao_perguntas', to='book.avaliacaoperguntas')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='avaliacaoitems_cliente', to='book.cliente')),
                ('id_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacaoitems_avaliacao', to='book.rotas')),
            ],
        ),
        migrations.CreateModel(
            name='avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_inicial', models.DateField(blank=True, null=True)),
                ('dt_final', models.DateField(blank=True, null=True)),
                ('pontos_fortes', models.TextField(blank=True, max_length=5000, null=True)),
                ('pontos_a_desenvolver', models.TextField(blank=True, max_length=5000, null=True)),
                ('assinatura_avaliador', models.TextField(blank=True, max_length=5000, null=True)),
                ('assinatura_avaliado', models.TextField(blank=True, max_length=5000, null=True)),
                ('fat_ant', models.FloatField(blank=True, null=True)),
                ('fat_antual', models.FloatField(blank=True, null=True)),
                ('id_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='avaliacao_avaliado', to=settings.AUTH_USER_MODEL)),
                ('id_avaliador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='avaliacao_avaliador', to=settings.AUTH_USER_MODEL)),
                ('id_rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_rota', to='book.rotas')),
            ],
        ),
        migrations.CreateModel(
            name='rotasClientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotasClientes_cliente', to='book.cliente')),
                ('id_rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotasClientes_rota', to='book.rotas')),
            ],
        ),
        migrations.CreateModel(
            name='visitaClientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_inicial', models.DateField(blank=True, null=True)),
                ('dt_final', models.DateField(blank=True, null=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='visitaClientes_cidade', to='book.cidades')),
                ('id_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='visitaClientes_avaliado', to=settings.AUTH_USER_MODEL)),
                ('id_avaliador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='visitaClientes_avaliador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='visitaClientesItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo', models.TextField(blank=True, max_length=5000, null=True)),
                ('status', models.TextField(blank=True, max_length=5000, null=True)),
                ('ult_compra', models.FloatField(blank=True, null=True)),
                ('negociacao_atual', models.FloatField(blank=True, null=True)),
                ('tipo_cliente', models.CharField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='visitaClientesItems_cliente', to=settings.AUTH_USER_MODEL)),
                ('id_comprador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='visitaClientesItems_comprador', to=settings.AUTH_USER_MODEL)),
                ('id_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitaClientesItems_visita', to='book.visitaclientes')),
            ],
        ),
    ]
