# Generated by Django 5.0.1 on 2024-08-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, max_length=255, null=True)),
                ('dtmov', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
