# Generated by Django 5.0.1 on 2024-08-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationsettings',
            name='idempresa',
            field=models.ForeignKey(db_column='idempresa', on_delete=django.db.models.deletion.CASCADE, to='acounts.empresa'),
        ),
    ]
