# Generated by Django 5.0.1 on 2024-08-28 05:34

import acounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_alter_presentationsettings_background_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationsettings',
            name='background_type',
            field=models.CharField(blank=True, choices=[('color', 'Cor'), ('url', 'Imagem'), ('urlf', 'Imagem com filtro'), ('colorf', 'Cor com filtro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='presentationsettings',
            name='background_url',
            field=models.ImageField(blank=True, null=True, upload_to=acounts.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='presentationsettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=acounts.models.get_image_upload_path),
        ),
    ]
