# Generated by Django 5.0.1 on 2024-08-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0005_presentationsettings_background_color_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationsettings',
            name='client_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
