# Generated by Django 5.0.1 on 2024-09-02 05:00

import acounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0006_presentationsettings_client_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationsettings',
            name='client_background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='client_background_color_mobile',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='client_background_type',
            field=models.CharField(blank=True, choices=[('color', 'Cor'), ('url', 'Imagem'), ('urlf', 'Imagem com filtro'), ('colorf', 'Cor com filtro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='client_background_type_mobile',
            field=models.CharField(blank=True, choices=[('color', 'Cor'), ('url', 'Imagem'), ('urlf', 'Imagem com filtro'), ('colorf', 'Cor com filtro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='client_background_url',
            field=models.ImageField(blank=True, null=True, upload_to=acounts.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='client_background_url_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=acounts.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='client_filter_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='client_filter_color_mobile',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='client_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
