# Generated by Django 5.0.1 on 2024-09-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0007_presentationsettings_client_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='modulo_cliente',
            field=models.BooleanField(default='False'),
        ),
    ]
