# Generated by Django 5.0.1 on 2024-09-02 14:09

import acounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0008_empresa_modulo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationsettings',
            name='logo_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=acounts.models.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='logo_text_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='presentationsettings',
            name='logo_type_mobile',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem')], default='text', max_length=10),
        ),
    ]
