# Generated by Django 5.0.1 on 2024-09-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0009_presentationsettings_logo_image_mobile_and_more'),
        ('cpfcli', '0007_cliente_codcli'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpfcli.cliente'),
        ),
    ]
