# Generated by Django 5.0.1 on 2024-09-21 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0010_profile_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cnpf_cnpj', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(blank=True, max_length=40, null=True)),
                ('cidade', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('bairro', models.CharField(blank=True, max_length=40, null=True)),
                ('rua', models.CharField(blank=True, max_length=40, null=True)),
                ('numero', models.CharField(blank=True, max_length=6, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('tipo_pessoa', models.CharField(blank=True, choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('codcli', models.BigIntegerField(blank=True, null=True)),
                ('ieent', models.CharField(blank=True, max_length=15, null=True)),
                ('codativ', models.IntegerField(blank=True, null=True)),
                ('ibge', models.IntegerField(blank=True, null=True)),
                ('aceita_comunicacao', models.BooleanField(default=True)),
                ('concordo_regulamento', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acounts.cliente'),
        ),
    ]
