# Generated by Django 5.0.1 on 2024-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0012_alter_cliente_cnpf_cnpj_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='aceita_comunicacao',
            field=models.BooleanField(default=False),
        ),
    ]
