# Generated by Django 5.0.1 on 2024-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0014_alter_profile_client_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='aceita_comunicacao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
