# Generated by Django 5.0.1 on 2024-10-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0015_alter_cliente_aceita_comunicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationsettings',
            name='error_message_suport',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
