# Generated by Django 5.0.1 on 2024-10-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0016_presentationsettings_error_message_suport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationsettings',
            name='error_message_suport',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
