# Generated by Django 5.0.1 on 2024-09-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0002_campanha_usa_numero_da_sorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponagem',
            name='numcaixa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuponagem',
            name='numpedecf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuponagem',
            name='tipo',
            field=models.CharField(default='NS', max_length=2),
        ),
    ]
