# Generated by Django 5.0.1 on 2024-09-07 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('idcampanha', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('dtultalt', models.DateTimeField()),
                ('dtinit', models.DateField()),
                ('dtfim', models.DateField()),
                ('multiplicador', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('usafornec', models.CharField(default='N', max_length=1)),
                ('usamarca', models.CharField(default='N', max_length=1)),
                ('usaprod', models.CharField(default='N', max_length=1)),
                ('ativo', models.CharField(max_length=1)),
                ('dtexclusao', models.DateTimeField(blank=True, null=True)),
                ('enviaemail', models.CharField(default='S', max_length=1)),
                ('tipointensificador', models.CharField()),
                ('fornecvalor', models.IntegerField(error_messages={'min_value': 'O valor do fornecedor não pode ser menor que 1.'}, validators=[django.core.validators.MinValueValidator(1)])),
                ('marcavalor', models.IntegerField(error_messages={'min_value': 'O valor da marca não pode ser menor que 1.'}, validators=[django.core.validators.MinValueValidator(1)])),
                ('prodvalor', models.IntegerField(error_messages={'min_value': 'O valor do produto não pode ser menor que 1.'}, validators=[django.core.validators.MinValueValidator(1)])),
                ('acumulativo', models.CharField()),
                ('restringe_fornec', models.CharField(default='N', max_length=1)),
                ('restringe_marca', models.CharField(default='N', max_length=1)),
                ('restringe_prod', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CampanhaFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcampanha', models.IntegerField(blank=True, null=True)),
                ('codfilial', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampanhaProcessados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcampanha', models.IntegerField(blank=True, null=True)),
                ('codfilial', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcampanha', models.IntegerField(default=0)),
                ('nomemarca', models.CharField(default='Sem descrição cadastrada')),
                ('codmarca', models.IntegerField(default=0)),
                ('dtmov', models.DateTimeField(blank=True, null=True)),
                ('intensificador', models.CharField(default='N')),
                ('restricao', models.CharField(default='N')),
            ],
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='CODCLI',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='CPFCNPJ',
            field=models.CharField(default='Sem cpf ou cnpj cadastrado'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='EMAIL',
            field=models.CharField(default='Sem email cadastrado'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='IDCAMPANHA',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='NOMECLI',
            field=models.CharField(default='Sem nome cadastrado'),
        ),
    ]
