# Generated by Django 5.0.1 on 2024-09-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0003_cuponagem_numcaixa_cuponagem_numpedecf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponagem',
            name='numped',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuponagem',
            name='numsorte',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
