# Generated by Django 5.0.1 on 2024-09-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0004_campanha_campanhafilial_campanhaprocessados_marcas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanhaprocessados',
            name='codfilial',
        ),
        migrations.AddField(
            model_name='campanhaprocessados',
            name='codcli',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campanhaprocessados',
            name='dtmov',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campanhaprocessados',
            name='historico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campanhaprocessados',
            name='numped',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
