# Generated by Django 5.0.1 on 2024-09-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0005_remove_campanhaprocessados_codfilial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcas',
            name='intensificador',
        ),
        migrations.RemoveField(
            model_name='marcas',
            name='restricao',
        ),
    ]
