# Generated by Django 5.0.1 on 2024-09-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0006_campanha_acumula_intensificadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codcli',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
