# Generated by Django 5.0.1 on 2024-09-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0006_remove_marcas_intensificador_remove_marcas_restricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcas',
            name='tipo',
            field=models.CharField(default='N'),
        ),
    ]
