# Generated by Django 5.0.1 on 2024-09-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0008_cliente_bairro_cliente_cnpf_cnpj_cliente_codativ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aceita_comunicacao',
            field=models.BooleanField(default=True),
        ),
    ]
