# Generated by Django 5.0.1 on 2024-09-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0008_alter_marcas_idcampanha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='idcampanha',
            field=models.IntegerField(default=0),
        ),
    ]
