# Generated by Django 5.0.1 on 2024-09-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0009_cliente_aceita_comunicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='concordo_regulamento',
            field=models.BooleanField(default=True),
        ),
    ]
