# Generated by Django 5.0.1 on 2024-09-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0009_alter_marcas_idcampanha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcampanha', models.IntegerField(default=0)),
                ('nomefornec', models.CharField(default='Sem descrição cadastrada')),
                ('codfornec', models.IntegerField(default=0)),
                ('dtmov', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(default='N')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcampanha', models.IntegerField(default=0)),
                ('nomeprod', models.CharField(default='Sem descrição cadastrada')),
                ('codprod', models.IntegerField(default=0)),
                ('dtmov', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(default='S')),
            ],
        ),
    ]
