# Generated by Django 5.0.1 on 2024-09-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0010_fornecedor_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuponagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtmov', models.DateField()),
                ('numped', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=12, max_digits=50)),
                ('numsorte', models.IntegerField()),
                ('codcli', models.IntegerField()),
                ('nomecli', models.TextField()),
                ('emailcli', models.TextField(blank=True, null=True)),
                ('telcli', models.TextField(blank=True, null=True)),
                ('cpf_cnpj', models.TextField(blank=True, null=True)),
                ('dataped', models.DateField()),
                ('bonificado', models.CharField(default='N', max_length=1)),
                ('ativo', models.CharField(default='S', max_length=1)),
                ('idcampanha', models.ForeignKey(db_column='idcampanha', on_delete=django.db.models.deletion.CASCADE, to='cpfcli.campanha')),
            ],
        ),
        migrations.CreateModel(
            name='CuponagemVencedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.IntegerField()),
                ('dtsorteio', models.DateTimeField()),
                ('numsorteio', models.IntegerField()),
                ('idcampanha', models.ForeignKey(db_column='idcampanha', on_delete=django.db.models.deletion.CASCADE, to='cpfcli.campanha')),
                ('numsorte', models.ForeignKey(db_column='numsorte', on_delete=django.db.models.deletion.CASCADE, to='cpfcli.cuponagem')),
            ],
        ),
        migrations.AddIndex(
            model_name='cuponagem',
            index=models.Index(fields=['dtmov', 'codcli', 'idcampanha'], name='MSCUPONAGEM_DTMOV_IDX'),
        ),
        migrations.AddIndex(
            model_name='cuponagem',
            index=models.Index(fields=['numsorte'], name='MSCUPONAGEM_NUMSORTE_IDX'),
        ),
        migrations.AddIndex(
            model_name='cuponagemvencedores',
            index=models.Index(fields=['idcampanha', 'codcli'], name='idx_campanha_cliente'),
        ),
    ]
