# Generated by Django 5.0.1 on 2024-09-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0011_cuponagem_cuponagemvencedores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponagemSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.IntegerField(db_column='CODCLI')),
                ('nomecli', models.TextField()),
                ('emailcli', models.TextField(blank=True, null=True)),
                ('telcli', models.TextField(blank=True, null=True)),
                ('cpf_cnpj', models.TextField(blank=True, null=True)),
                ('idcampanha', models.IntegerField(db_column='IDCAMPANHA')),
                ('saldo', models.IntegerField(db_column='SALDO')),
                ('dtmov', models.DateTimeField(db_column='DTMOV')),
            ],
            options={
                'verbose_name': 'Saldo de Cupom',
                'verbose_name_plural': 'Saldos de Cupons',
            },
        ),
    ]
