# Generated by Django 5.0.1 on 2024-09-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0012_cuponagemsaldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhaprocessados',
            name='geroubonus',
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='campanhaprocessados',
            name='geroucupom',
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
    ]
