# Generated by Django 5.0.1 on 2024-09-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0012_campanha_logo_campanha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuponagem',
            name='bonificado',
        ),
        migrations.AddField(
            model_name='cuponagem',
            name='tipogeracao',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='logo_campanha',
            field=models.ImageField(blank=True, null=True, upload_to='campanha/'),
        ),
    ]
