# Generated by Django 5.0.1 on 2024-09-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0013_campanhaprocessados_geroubonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhaprocessados',
            name='numped',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuponagem',
            name='numped',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cuponagem',
            name='numsorte',
            field=models.BigIntegerField(),
        ),
    ]
