# Generated by Django 5.0.1 on 2024-09-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0013_remove_cuponagem_bonificado_cuponagem_tipogeracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponagem',
            name='bonificado',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
