# Generated by Django 5.0.1 on 2024-09-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0015_campanhaprocessados_tipoprocessamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='autorizacao_campanha',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='campanha',
            name='regulamento',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
