# Generated by Django 5.0.1 on 2024-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0017_campanha_limite_intensificadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='regulamento',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
