# Generated by Django 5.0.1 on 2024-09-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0018_alter_campanha_regulamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='regulamento',
            field=models.TextField(blank=True, max_length=30000, null=True),
        ),
    ]
