# Generated by Django 5.0.1 on 2024-09-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0019_alter_campanha_regulamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponagem',
            name='numcupom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuponagem',
            name='qtcupons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
