# Generated by Django 5.0.1 on 2024-09-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0020_cuponagem_numcupom_cuponagem_qtcupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponagem',
            name='valor_total_venda_cupom',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=50, null=True),
        ),
    ]
