# Generated by Django 5.0.1 on 2024-10-01 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0021_cuponagem_valor_total_venda_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='idcampanha',
            field=models.ForeignKey(db_column='idcampanha', on_delete=django.db.models.deletion.CASCADE, to='cpfcli.campanha'),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='idcampanha',
            field=models.ForeignKey(db_column='idcampanha', on_delete=django.db.models.deletion.CASCADE, to='cpfcli.campanha'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='idcampanha',
            field=models.ForeignKey(db_column='idcampanha', on_delete=django.db.models.deletion.CASCADE, to='cpfcli.campanha'),
        ),
    ]
