# Generated by Django 5.0.1 on 2024-10-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0023_alter_blacklist_idcampanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='background_campanha',
            field=models.ImageField(blank=True, null=True, upload_to='campanha/'),
        ),
    ]
