# Generated by Django 5.0.1 on 2024-10-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0024_campanha_background_campanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='restringe_tipo_client',
            field=models.CharField(default='T', max_length=1),
        ),
    ]
