# Generated by Django 5.0.1 on 2025-01-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0025_campanha_restringe_tipo_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponagemvencedores',
            name='numsorte',
            field=models.IntegerField(),
        ),
    ]
