# Generated by Django 5.0.1 on 2025-04-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpfcli', '0026_alter_cuponagemvencedores_numsorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='mensagemcampanha',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='campanha',
            name='texto_cor_mensagem_caixa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campanha',
            name='texto_mensagem_caixa',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='campanha',
            name='url_mensagem_caixa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='restringe_tipo_client',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
